/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlkhproject;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        //Placeholder
        addPlaceholder(textID);
        addPlaceholder(textPass);
    }
    
    public void addPlaceholder (JTextField textField ){
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }
    public void removePlaceholder (JTextField textField ){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN| Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textID = new javax.swing.JTextField();
        checkBoxRemidPass = new javax.swing.JCheckBox();
        textResetPass = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        textPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        setMaximumSize(new java.awt.Dimension(900, 680));
        setMinimumSize(new java.awt.Dimension(900, 680));
        setPreferredSize(new java.awt.Dimension(900, 680));
        setSize(new java.awt.Dimension(900, 680));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        textID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textID.setText("ID nhân viên");
        textID.setToolTipText("");
        textID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textIDFocusLost(evt);
            }
        });
        textID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textIDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textIDMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textIDMousePressed(evt);
            }
        });
        getContentPane().add(textID);
        textID.setBounds(320, 230, 294, 44);

        checkBoxRemidPass.setForeground(new java.awt.Color(204, 255, 204));
        checkBoxRemidPass.setText("Lưu mật khẩu ");
        getContentPane().add(checkBoxRemidPass);
        checkBoxRemidPass.setBounds(320, 380, 99, 20);

        textResetPass.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        textResetPass.setForeground(new java.awt.Color(0, 255, 0));
        textResetPass.setText("Quên mật khẩu ? ");
        textResetPass.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                textResetPassAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        textResetPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textResetPassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textResetPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textResetPassMouseExited(evt);
            }
        });
        getContentPane().add(textResetPass);
        textResetPass.setBounds(500, 500, 120, 20);

        buttonLogin.setBackground(new java.awt.Color(0, 255, 51));
        buttonLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setText("Đăng nhập ");
        buttonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonLoginMouseExited(evt);
            }
        });
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLogin);
        buttonLogin.setBounds(410, 430, 128, 39);

        textPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textPass.setText("Mật khẩu");
        textPass.setEchoChar('\u0000');
        textPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textPassFocusLost(evt);
            }
        });
        textPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textPassMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textPassMousePressed(evt);
            }
        });
        getContentPane().add(textPass);
        textPass.setBounds(320, 310, 294, 44);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive - Trường ĐH CNTT - University of Information Technology\\Ảnh\\Saved Pictures\\javaQLKH\\loginBackground01.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 10, 450, 600);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive - Trường ĐH CNTT - University of Information Technology\\Ảnh\\Saved Pictures\\javaQLKH\\loginBackground02.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void textIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textIDFocusGained
        if(textID.getText().equals("ID nhân viên")){
            textID.setText(null);
            textID.requestFocus();
            removePlaceholder(textID);
        }
    }//GEN-LAST:event_textIDFocusGained

    private void textIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textIDFocusLost
        if(textID.getText().length()== 0){
            addPlaceholder(textID);
            textID.setText("ID nhân viên");
        }
    }//GEN-LAST:event_textIDFocusLost

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        if(textID.getText().equals("ID nhân viên")||textPass.getText().equals("Mật khẩu")){
            JOptionPane.showMessageDialog(null,"ID nhân viên hoặc Mật khẩu không được để trống","Thông báo",JOptionPane.ERROR_MESSAGE);
        }
        new NhanVien_CaNhan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void textResetPassAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_textResetPassAncestorAdded
        
    }//GEN-LAST:event_textResetPassAncestorAdded

    private void textResetPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textResetPassMouseClicked
        new ForgotPassword().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_textResetPassMouseClicked

    private void textPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPassFocusGained
        if(textPass.getText().equals("Mật khẩu")){
            textPass.setText(null);
            textPass.requestFocus();
            textPass.setEchoChar('*');
            removePlaceholder(textPass);
        }
    }//GEN-LAST:event_textPassFocusGained

    private void textPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPassFocusLost
        if(textPass.getText().length()== 0){
            addPlaceholder(textPass);
            textPass.setEchoChar('\u0000');
            textPass.setText("Mật khẩu");
        }
    }//GEN-LAST:event_textPassFocusLost

    private void textResetPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textResetPassMouseEntered
        textResetPass.setForeground(Color.white);
    }//GEN-LAST:event_textResetPassMouseEntered

    private void textResetPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textResetPassMouseExited
        textResetPass.setForeground(Color.green);
    }//GEN-LAST:event_textResetPassMouseExited

    private void textIDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textIDMouseEntered
        textID.setBorder(BorderFactory.createBevelBorder(0, Color.green, Color.white));
    }//GEN-LAST:event_textIDMouseEntered

    private void textIDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textIDMouseExited
        textID.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_textIDMouseExited

    private void textIDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textIDMousePressed
        textID.setBorder(BorderFactory.createBevelBorder(1, Color.green, Color.white));
    }//GEN-LAST:event_textIDMousePressed

    private void textPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textPassMouseEntered
        textPass.setBorder(BorderFactory.createBevelBorder(0, Color.green, Color.white));
    }//GEN-LAST:event_textPassMouseEntered

    private void textPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textPassMouseExited
        textPass.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_textPassMouseExited

    private void textPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textPassMousePressed
        textPass.setBorder(BorderFactory.createBevelBorder(1, Color.green, Color.white));
    }//GEN-LAST:event_textPassMousePressed

    private void buttonLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseEntered
        buttonLogin.setBorder(BorderFactory.createEtchedBorder(Color.lightGray, Color.green));
        buttonLogin.setBackground(Color.blue);
    }//GEN-LAST:event_buttonLoginMouseEntered

    private void buttonLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseExited
        buttonLogin.setBorder(BorderFactory.createEmptyBorder());
        buttonLogin.setBackground(Color.green);
    }//GEN-LAST:event_buttonLoginMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JCheckBox checkBoxRemidPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textID;
    private javax.swing.JPasswordField textPass;
    private javax.swing.JLabel textResetPass;
    // End of variables declaration//GEN-END:variables
}
