/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlkhproject;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class ResetPassword extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public ResetPassword() {
        initComponents();
        
        //Placeholder
        addPlaceholder(textID);
        addPlaceholder(textPass);
    }
    
    public void addPlaceholder (JTextField textField ){
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }
    public void removePlaceholder (JTextField textField ){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN| Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textID = new javax.swing.JTextField();
        buttonLogin = new javax.swing.JButton();
        textPass = new javax.swing.JPasswordField();
        textResetPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));

        textID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textID.setText("ID nhân viên");
        textID.setToolTipText("");
        textID.setEnabled(false);
        textID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textIDFocusLost(evt);
            }
        });

        buttonLogin.setBackground(new java.awt.Color(0, 255, 51));
        buttonLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setText("Đổi mật khẩu");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        textPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textPass.setText("Mật khẩu");
        textPass.setEchoChar('\u0000');
        textPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textPassFocusLost(evt);
            }
        });

        textResetPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textResetPass.setText("Nhập lại mật khẩu");
        textResetPass.setEchoChar('\u0000');
        textResetPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textResetPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textResetPassFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textID, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(textPass)
                            .addComponent(textResetPass))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonLogin)
                        .addGap(143, 143, 143))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(textPass, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(textResetPass, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textIDFocusGained
        // TODO add your handling code here:
        if(textID.getText().equals("ID nhân viên")){
            textID.setText(null);
            textID.requestFocus();
            removePlaceholder(textID);
        }
    }//GEN-LAST:event_textIDFocusGained

    private void textIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textIDFocusLost
        // TODO add your handling code here:
        if(textID.getText().length()== 0){
            addPlaceholder(textID);
            textID.setText("ID nhân viên");
        }
    }//GEN-LAST:event_textIDFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void textPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPassFocusGained
        // TODO add your handling code here:
        if(textPass.getText().equals("Mật khẩu")){
            textPass.setText(null);
            textPass.requestFocus();
            textPass.setEchoChar('*');
            removePlaceholder(textPass);
        }
    }//GEN-LAST:event_textPassFocusGained

    private void textPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPassFocusLost
        // TODO add your handling code here:
        if(textPass.getText().length()== 0){
            addPlaceholder(textPass);
            textPass.setEchoChar('\u0000');
            textPass.setText("Mật khẩu");
        }
    }//GEN-LAST:event_textPassFocusLost

    private void textResetPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textResetPassFocusGained
        // TODO add your handling code here:
        if(textResetPass.getText().equals("Nhập lại mật khẩu")){
            textResetPass.setText(null);
            textResetPass.requestFocus();
            textResetPass.setEchoChar('*');
            removePlaceholder(textResetPass);
        }
    }//GEN-LAST:event_textResetPassFocusGained

    private void textResetPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textResetPassFocusLost
        // TODO add your handling code here:
        if(textResetPass.getText().length()== 0){
            addPlaceholder(textResetPass);
            textResetPass.setEchoChar('\u0000');
            textResetPass.setText("Nhập lại mật khẩu");
        }
    }//GEN-LAST:event_textResetPassFocusLost

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(null,textPass.getText(),"Thông báo",JOptionPane.ERROR_MESSAGE);
//        JOptionPane.showMessageDialog(null,textResetPass.getText(),"Thông báo",JOptionPane.ERROR_MESSAGE);
        if(textPass.getText().equals(textResetPass.getText())){
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_buttonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textID;
    private javax.swing.JPasswordField textPass;
    private javax.swing.JPasswordField textResetPass;
    // End of variables declaration//GEN-END:variables
}
